import type { Analysis } from "./analyze";

const DECISION_TEXT = {
  sign: "Looks reasonable to sign",
  negotiate: "Negotiate before signing",
  consult: "Consult a lawyer before signing",
} as const;

/**
 * Builds a plain-text brief the user can take to a lawyer or the other party.
 * Only verified or approximate evidence is quoted; unverified items are labelled.
 */
export function buildLawyerBrief(analysis: Analysis, generatedAt = new Date()): string {
  const clauseLabel = (id: string | null) => analysis.clauses.find((c) => c.id === id);
  const lines: string[] = [
    "DOCLENS: PRE-SIGNING BRIEF",
    `Generated: ${generatedAt.toISOString().slice(0, 10)}`,
    `Document: ${analysis.documentType}`,
    `Recommendation: ${DECISION_TEXT[analysis.verdict.decision]} (${analysis.verdict.reason})`,
    "",
    "SUMMARY",
    analysis.summary,
    "",
    "KEY TERMS",
    ...analysis.keyTerms.map((t) => `- ${t.label}: ${t.value}${t.verification === "unverified" ? " (not verified)" : ""}`),
    "",
    "CLAUSES OF CONCERN",
  ];

  analysis.risks.forEach((risk, i) => {
    const clause = clauseLabel(risk.verification.clauseId);
    const where = clause ? `${clause.label}, page ${clause.page}` : "location not verified";
    lines.push(
      `${i + 1}. [${risk.severity.toUpperCase()}] ${risk.title} (${where})`,
      `   Text: "${risk.quote}"`,
      `   Why it matters: ${risk.whyItMattersToYou}`,
      `   Ask for: ${risk.suggestedAction}`,
    );
  });

  if (analysis.missingProtections.length) {
    lines.push("", "MISSING PROTECTIONS");
    analysis.missingProtections.forEach((m) => lines.push(`- ${m.title}: ${m.explanation}`));
  }

  lines.push("", "QUESTIONS TO ASK");
  analysis.lawyerQuestions.forEach((q, i) => lines.push(`${i + 1}. ${q}`));

  lines.push(
    "",
    "Note: This brief was generated by AI to help you prepare. It is not legal advice.",
  );
  return lines.join("\n");
}
